import { useEffect, useState } from 'react';
import { LayoutDashboard, Users, Store, Package, ClipboardCheck, ShoppingBag, CreditCard, MessageSquare, ArrowUpRight, RefreshCw, ShieldCheck } from 'lucide-react';
import { money, useResource } from '../api';
import type { VendorApplication } from '../types';
import { Empty, Feedback, Loading } from './UI';
import { AuditHistory, type AuditEvent } from './AdminShared';
import AdminDirectory from './AdminDirectory';
import AdminProducts from './AdminProducts';
import { Application, Payments } from './AdminOperations';
import Orders from './Orders';
import Disputes from './Disputes';
const sections=[{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'accounts',label:'Accounts',icon:Users},{id:'vendors',label:'Vendors',icon:Store},{id:'products',label:'Products',icon:Package},{id:'applications',label:'Applications',icon:ClipboardCheck},{id:'orders',label:'Orders',icon:ShoppingBag},{id:'payments',label:'Payments',icon:CreditCard},{id:'support',label:'Support',icon:MessageSquare}];
interface Overview { metrics:Record<string,number>;trend:{date:string;orders:number;paid:number}[];activity:AuditEvent[] }
function Applications({revision,onChange}:{revision:number;onChange:()=>void}) {
 const [filter,setFilter]=useState('Pending');const resource=useResource<{applications:VendorApplication[]}>('/admin/applications',revision);const list=resource.data?.applications.filter(item=>!filter||item.status===filter);
 return <><div className="section-title"><h2>Seller applications</h2><label>Status<select value={filter} onChange={e=>setFilter(e.target.value)}>{['Pending','Approved','Rejected',''].map(value=><option key={value} value={value}>{value||'All applications'}</option>)}</select></label></div><Feedback error={resource.error}/>{resource.loading?<Loading/>:!list?.length?<Empty>No {filter.toLowerCase()} applications.</Empty>:list.map(application=><Application key={application.id} application={application} onChange={onChange}/>)}</>;
}
function OverviewPanel({data,onNavigate}:{data:Overview;onNavigate:(tab:string)=>void}) {
 const m=data.metrics;const max=Math.max(1,...data.trend.map(day=>day.orders));
 return <><div className="admin-welcome"><div><p className="eyebrow">MARKETPLACE AT A GLANCE</p><h2>Keep good things growing.</h2><p>Stay close to your community, stores and daily operations.</p></div><div className="admin-welcome-mark" aria-hidden="true"><ShieldCheck size={54}/></div></div><div className="admin-stat-grid">{[{label:'Marketplace accounts',value:m.users,tab:'accounts',icon:Users,note:`${m.suspended_accounts} suspended`},{label:'Active vendors',value:m.vendors,tab:'vendors',icon:Store,note:'Explore your store directory'},{label:'Published products',value:m.products,tab:'products',icon:Package,note:`${m.delisted_products} admin delisted`},{label:'Paid order value',value:money(m.paid_value),tab:'orders',icon:ShoppingBag,note:`${m.orders} total orders`}].map(card=><button className="admin-stat" key={card.tab} onClick={()=>onNavigate(card.tab)}><span className="admin-stat-top"><card.icon size={19}/><ArrowUpRight size={16}/></span><span className="muted small">{card.label}</span><strong>{card.value}</strong><span className="small muted">{card.note}</span></button>)}</div><div className="admin-overview-grid"><section className="admin-surface"><div className="section-title"><div><p className="eyebrow">LAST 7 DAYS</p><h2>Order activity</h2></div><button className="text-button" onClick={()=>onNavigate('orders')}>View orders →</button></div><div className="admin-chart" aria-label="Orders placed per day over the last seven days">{data.trend.map(day=><div className="admin-chart-column" key={day.date}><span className="small">{day.orders}</span><div className="admin-chart-track"><div className="admin-chart-bar" style={{height:`${Math.max(2,day.orders/max*100)}%`,opacity:day.orders?1:.25}} title={`${day.date}: ${day.orders} orders, ${money(day.paid)} paid order value`}/></div><span className="small muted">{new Date(day.date+'T12:00:00').toLocaleDateString('en-NG',{weekday:'short'})}</span></div>)}</div><p className="small muted">Daily order count, including cancelled orders. Hover a bar for paid value.</p></section><section className="admin-surface"><p className="eyebrow">REVIEW QUEUE</p><h2>Needs attention</h2>{[{label:'Seller applications',value:m.pending_applications,tab:'applications'},{label:'Open tickets',value:m.open_complaints,tab:'support'},{label:'Flagged products',value:m.flagged_products,tab:'products'},{label:'Flagged accounts',value:m.flagged_accounts,tab:'accounts'}].map(item=><button className="admin-queue-item" key={item.tab} onClick={()=>onNavigate(item.tab)}><span>{item.label}</span><strong>{item.value}</strong><ArrowUpRight size={16}/></button>)}</section></div><section className="admin-surface"><p className="eyebrow">ACCOUNTABILITY</p><h2>Recent moderation activity</h2><AuditHistory events={data.activity}/></section></>;
}
export default function AdminDashboard({revision,onChange}:{revision:number;onChange:()=>void}) {
 const currentTab=()=>{const name=window.location.hash.slice(1).split('?')[0].split('/')[1];return sections.some(section=>section.id===name)?name:'overview';};
 const [tab,setCurrentTab]=useState(currentTab);const setTab=(value:string)=>{window.location.hash='admin/'+value;};
 useEffect(()=>{const update=()=>setCurrentTab(currentTab());window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);const overview=useResource<Overview>('/admin/overview',revision);
 return <div className="admin-layout"><aside className="admin-sidebar"><div className="admin-sidebar-brand"><ShieldCheck size={23}/><div>Edible admin<small>MARKETPLACE CONTROL</small></div></div><nav aria-label="Administration sections">{sections.map(item=><button key={item.id} className={tab===item.id?'active':''} aria-current={tab===item.id?'page':undefined} onClick={()=>setTab(item.id)}><item.icon size={18}/><span>{item.label}</span>{item.id==='applications'&&!!overview.data?.metrics.pending_applications&&<small>{overview.data.metrics.pending_applications}</small>}</button>)}</nav><div className="admin-sidebar-footer"><span className="admin-online-dot"/>Administrator workspace<a href="#catalog">Visit marketplace ↗</a></div></aside><div className="admin-workspace"><header className="admin-page-header"><div><p className="eyebrow">ADMINISTRATION / {tab.toUpperCase()}</p><h1>{sections.find(item=>item.id===tab)?.label}</h1></div><button className="button secondary" onClick={onChange}><RefreshCw size={15}/>Refresh</button></header><Feedback error={overview.error}/>{tab==='overview'&&(overview.loading?<Loading/>:overview.data&&<OverviewPanel data={overview.data} onNavigate={setTab}/>)}{(tab==='accounts'||tab==='vendors')&&<AdminDirectory key={tab} vendors={tab==='vendors'} revision={revision} onChange={onChange}/>} {tab==='products'&&<AdminProducts revision={revision} onChange={onChange}/>} {tab==='applications'&&<Applications revision={revision} onChange={onChange}/>} {tab==='orders'&&<Orders mode="admin" revision={revision} onChange={onChange}/>} {tab==='payments'&&<Payments revision={revision} onChange={onChange}/>} {tab==='support'&&<Disputes admin revision={revision} onChange={onChange}/>}</div></div>;
}
