import { useState, type FormEvent } from 'react';
import { money, mutate, useAction } from '../api';
import { Feedback } from './UI';
export interface Merchandising {id:string;priceMinor:number;featured:boolean;saleKind:'promo'|'flash'|null;salePriceMinor:number|null;saleStartsAt:string|null;saleEndsAt:string|null}
function localDate(value:string|null){if(!value)return '';const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export default function MerchandisingEditor({product,onChange}:{product:Merchandising;onChange:()=>void}) {
 const [kind,setKind]=useState(product.saleKind||'');const action=useAction(onChange);
 const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);void action.run(()=>mutate('/admin/products/'+product.id+'/merchandising','PATCH',{featured:form.has('featured'),sale:kind?{kind,priceMinor:Math.round(Number(form.get('price'))*100),startsAt:new Date(String(form.get('startsAt'))).toISOString(),endsAt:new Date(String(form.get('endsAt'))).toISOString()}:null}),'Home page placement updated.');};
 return <section className="admin-moderation"><h3>Home page & promotions</h3><p className="muted small">Feature this product or schedule a discounted offer. Best sellers are ranked automatically from delivered, paid purchases.</p><Feedback error={action.error} success={action.success}/><form className="form-stack" onSubmit={submit}><label className="check-label"><input type="checkbox" name="featured" defaultChecked={product.featured}/>Show in featured products</label><label>Promotion<select value={kind} onChange={event=>setKind(event.target.value)}><option value="">No promotion</option><option value="promo">Promo</option><option value="flash">Flash sale</option></select></label>{kind&&<><label>Sale price (NGN) · regular price {money(product.priceMinor)}<input name="price" type="number" step="0.01" min="0.01" max={(product.priceMinor-1)/100} defaultValue={product.salePriceMinor===null?'':product.salePriceMinor/100} required/></label><div className="form-grid"><label>Starts (your local time)<input name="startsAt" type="datetime-local" defaultValue={localDate(product.saleStartsAt)} required/></label><label>Ends (your local time)<input name="endsAt" type="datetime-local" defaultValue={localDate(product.saleEndsAt)} required/></label></div><p className="small muted">The sale price applies to browsing, baskets and new checkouts only during this window.</p></>}<button className="button primary" disabled={action.busy}>{action.busy?'Saving…':'Save placement & promotion'}</button></form></section>;
}
